// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var edgeHandlesDefaults, graphStyles;
    graphStyles = '';
    $.ajax({
      async: false,
      type: 'GET',
      url: 'compiled/web-graph.css',
      success: function(data) {
        return graphStyles = data;
      }
    });
    edgeHandlesDefaults = {
      preview: true,
      handleSize: 20,
      handleColor: "#ff0000",
      handleLineType: "ghost",
      handleLineWidth: 2,
      handleNodes: "node",
      hoverDelay: 150,
      cxt: true,
      enabled: true,
      toggleOffOnLeave: false
    };
    $("#cy").cytoscape({
      style: graphStyles,
      ready: function() {
        window.cy = this;
        cy.on("tap", function(e) {
          if (e.cyTarget === cy) {
            return cy.add({
              group: "nodes",
              position: e.cyPosition
            });
          }
        });
        return cy.edgehandles(edgeHandlesDefaults);
      }
    });
    return $('#layout-arbor').click(function() {
      return cy.layout({
        name: 'arbor'
      });
    });
  });

}).call(this);
