// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var edgeHandlesDefaults, graphStyles;
    graphStyles = '';
    $.ajax({
      async: false,
      type: 'GET',
      url: 'compiled/web-graph.css',
      success: function(data) {
        return graphStyles = data;
      }
    });
    edgeHandlesDefaults = {
      preview: true,
      handleSize: 20,
      handleColor: "#ff0000",
      handleLineType: "ghost",
      handleLineWidth: 2,
      handleNodes: "node",
      hoverDelay: 150,
      cxt: true,
      enabled: true,
      toggleOffOnLeave: false
    };
    $("#cy").cytoscape({
      style: graphStyles,
      ready: function() {
        window.cy = this;
        cy.on("tap", function(e) {
          if (e.cyTarget === cy) {
            return cy.add({
              group: "nodes",
              position: e.cyPosition
            });
          }
        });
        return cy.edgehandles(edgeHandlesDefaults);
      }
    });
    $('#layout-arbor').click(function() {
      return cy.layout({
        name: 'arbor'
      });
    });
    $('#save-json').click(function() {
      $(this).attr('download', (($('#save-file-name')).val() || 'graph') + '.json');
      return $(this).attr('href', "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(cy.elements().jsons())));
    });
    return $('#load-json').change(function(evt) {
      var file, reader;
      file = evt.target.files[0];
      reader = new FileReader();
      reader.onload = function(event) {
        console.log(JSON.parse(event.target.result)['elements']);
        return cy.add(JSON.parse(event.target.result));
      };
      return reader.readAsText(file);
    });
  });

}).call(this);
